### ISSUE TITLE
FTP service bug

### ISSUE THREAD

**Issue by clapilgrim** [kroese/virtual-dsm#245]
I can't use ftp. 
There is something wrong?

![Immagine](https://github.com/kroese/virtual-dsm/assets/14829189/0fe2a3e2-2e33-4990-9c63-22bf5811bca3)

![AQ](https://github.com/kroese/virtual-dsm/assets/14829189/b3318a47-5af8-4c62-bcb8-eeb71892bcb3)

**Comment by clapilgrim** [comment]
I tried both active mode and passive mode... unfortunately it doesn't work.. instead on my synology DS114 with DSM 7.1.1 it works perfectly.  I also tried to restore my DS114 backup settings, on docker, but without success. Can you help me?

**Comment by clapilgrim** [comment]
have you tried if it works?  i can't get it to work in Active mode

**Comment by clapilgrim** [comment]
The firewall in DSM is not active.

I keep trying..

Filezilla can't get into FTP. crashes at: "Retrieving directory listing..."

I also tried with macvlan but it doesn't work.
Is these settings correct?
```
version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        cap_add:
            - NET_ADMIN                       
        ports:
            - 5000:5000
            - 20:20
            - 21:21
        volumes:
            - /opt/dsm:/storage
        restart: on-failure
        stop_grace_period: 1m

        networks:
            dockervlan:
               ipv4_address: 192.168.1.60

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp0s10
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.64/26"
          gateway: "192.168.1.1"
```
