### ISSUE TITLE
Issue when Downloading VirtualDSM

### ISSUE THREAD

**Issue by fatez** [kroese/virtual-dsm#272]
Here the log from docker :

```
dsm    | ❯ Starting Virtual DSM for Docker v4.06...
dsm    | ❯ Install: Downloading DSM_VirtualDSM_64561.pat...
dsm    | ❯ ERROR: Failed to download https://global.synologydownload.com/download/DSM/release/7.2/64561/DSM_VirtualDSM_64561.pat, reason: 8
dsm    | ❯ Install: Downloading DSM_VirtualDSM_64561.pat...
dsm    | ❯ ERROR: Failed to download https://global.synologydownload.com/download/DSM/release/7.2/64561/DSM_VirtualDSM_64561.pat, reason: 8
dsm exited with code 69
dsm    | ❯ Install: Downloading DSM_VirtualDSM_64561.pat...
dsm    | ❯ ERROR: Failed to download https://global.synologydownload.com/download/DSM/release/7.2/64561/DSM_VirtualDSM_64561.pat, reason: 8
dsm exited with code 69
```

my docker-compose.yml:

```
version: "3"
services:
    dsm:
        container_name: dsm
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "40G"
            ALLOCATE: "N"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        cap_add:
            - NET_ADMIN
        ports:
            - 5050:5000
        volumes:
            - /Synology/:/storage
        restart: on-failure
        stop_grace_period: 1m
```
