### ISSUE TITLE
Network problem during account login

### ISSUE THREAD

**Issue by Sharrrrk** [kroese/virtual-dsm#300]
Hello @kroese , I just met a strange problem that I can only perform synology account login with proxy enabled on vdsm. If I disable the proxy for vdsm, the login would fail. I also saw some error message on the bottom on "external access" configuration page writing connection problem, check DNS or network configuration bla bla.., but package center, update check, everything working just fine, ping to gateway and external servers all good, so I'm quite confused why only having problem with account login...

Do you have any clue about this problem?

**Environment**
I am using macvlan with DHCP enabled. The IP of either container itself and dsm works fine.

Host machine: virtual machine with Ubuntu 22.04

My docker compose yml as below with some information musked.
```
version: "3"
services:
  dsm:
    container_name: vdsm
    image: kroese/virtual-dsm:latest
    environment:
      DISK_SIZE: "32G"
      ALLOCATE: "N"
      CPU_CORES: "2"
      RAM_SIZE: "1024M"
      DHCP: "Y"
      URL: "https://global.synologydownload.com/download/DSM/release/7.2/64570-1/DSM_VirtualDSM_64570.pat"
      MAC: "xxxxxx"
      GUEST_SERIAL: "xxxxxx"
      HOST_SERIAL: "xxxxxx"
      HOST_MAC: "xxxxxx"
      HOST_MODEL: "xxxxxx"
    networks:
      vdsm:
        ipv4_address: 192.168.1.x
    devices:
      - /dev/kvm
      - /dev/vhost-net
    device_cgroup_rules:
      - 'c 236:* rwm'
    cap_add:
      - NET_ADMIN
    ports:
      - 5000:5000
    volumes:
      - /xxxxxx:/storage
    restart: unless-stopped
    stop_grace_period: 1m
networks:
  vdsm:
    external: true
```

My macvlan information:
```
$ docker network inspect vdsm
[
    {
        "Name": "vdsm",
        "Id": "def301695df6470cda1955343f763d826392e499856a7eb41a5feaefcac48338",
        "Created": "2023-07-20T06:18:31.763058368Z",
        "Scope": "local",
        "Driver": "macvlan",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.1.0/24",
                    "Gateway": "192.168.1.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "c607a066da0f75f12c33e33207d9d283922ef0991c11bd92cd57c558048f10a3": {
                "Name": "vdsm-dsm-run-4fa770c50b7d",
                "EndpointID": "12bd71f649bdd2220c403d525b0c85865f7d80a9f859a8347ac97607d976d84e",
                "MacAddress": "XXX",
                "IPv4Address": "192.168.1.XXX/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "parent": "enp6s18"
        },
        "Labels": {}
    }
]
```
