### ISSUE TITLE
Unable to send verification mail for 2FA

### ISSUE THREAD

**Issue by Phorze** [kroese/virtual-dsm#313]
Getting the following error:

![Screenshot 2023-08-17 132158](https://github.com/kroese/virtual-dsm/assets/5550550/75556f9b-25bd-481a-bd33-f2fc3d33cc40)

But no sign of an error code. Any log file in /var/log i could be looking at?

**Comment by Phorze** [comment]
There isn't for me:
![Screenshot 2023-08-17 172022](https://github.com/kroese/virtual-dsm/assets/5550550/d40edcae-0701-4de6-ad4c-24e68e88d2ba)

**Comment by Phorze** [comment]
Test email was sent, but doesn't seem it was actually sent/delivered.

**Comment by Phorze** [comment]
So is it actually working for others? I tried both Gmail and Outlook via the oauth method.. so seems pretty failsafe to me

**Comment by Phorze** [comment]
Now tested using Sendgrid, smtp with api/password. No error but sendgrid is not detecting an email (also not receiving the email) I'm sure the problem is at my end but i don't know where to start. I am running behind a reverse proxy but surely that shouldnt be a problem for outgouing traffic.

**Comment by Siyuanw** [comment]
Potentially the same issue here... not able to send emails after setting up email notification. I set up an SMTP server and can confirm it doesn't receive any requests.

Not sure if it's related to `synodsmnotify`.

Getting some errors in `/var/log/messages` about it.

> 2023-09-09T19:47:08+01:00 dsm synodsmnotify[26954]: stringdb.cpp:173 Failed to query ImproperShutdownFrequently sql:SELECT source FROM 'category' WHERE tag='ImproperShutdownFrequently' LIMIT 1
> 2023-09-09T19:47:08+01:00 dsm synodsmnotify[26954]: synodsmnotify.cpp:919 Fail to send notify ImproperShutdownFrequently to @administrators

**Comment by Siyuanw** [comment]
thank you @kroese.

> Are you using bridge networking or macvlan+dhcp?

bridge. Not sure if it's a bug: the vdsm has no internet access in bridge mode as it cannot sync NTP and cannot check system update. However, it CAN download package.

Not sure why I cannot use macvlan+dhcp. Getting below error

```
RTNETLINK answers: Operation not supported
❯ ERROR: Cannot create macvtap interface. Please make sure the network type is 'macvlan' and not 'ipvlan',
❯ ERROR: and that the NET_ADMIN capability has been added to the container config: --cap-add NET_ADMIN
❯ Starting Virtual DSM for Docker v4.19...
```

> Have you configured a valid serialnumber for DSM or are you using the default (00000000000)?

I was using default. And I tried to apply the valid vdsm serial but no luck with sending notification.

> Are you logged in to your Synology account or not?

yes in host. no in guest (vdsm).

> Can you post your compose-file here so I can look at the settings?

here you go. I commented network part as getting error when running macvlan.

```yaml
version: "3"
services:
    dsm:
        image: kroese/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
            ALLOCATE: "N"
            CPU_CORES: "2"
            RAM_SIZE: "1024M"
            HOST_SERIAL: "_MASKED_"
            GUEST_SERIAL: "_MASKED_"
            # DHCP: "Y"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
        volumes:
            - storage:/storage
        restart: on-failure
        stop_grace_period: 1m
        # networks:
            # vdsm:
                # ipv4_address: 192.168.1.100
volumes:
    storage:
networks:
    vdsm:
        external: true
```

also, here's the command when creating docker network

```shell
sudo docker network create -d macvlan \
    --subnet=192.168.1.0/24 \
    --gateway=192.168.1.1 \
    --ip-range=192.168.1.100/28 \
    -o parent=ovs_eth0 vdsm
```
